---
- name: Deploy application to EKS
  hosts: 65.0.61.220
  become: yes

  tasks:

  - name: Configure kubectl for EKS cluster
    command: aws eks --region ap-south-1 update-kubeconfig --name my-eks-cluster

  - name: Copy Kubernetes manifest file
    copy:
      src: deployment.yaml
      dest: /home/ec2-user/deployment.yaml

  - name: Deploy application to EKS
    command: kubectl apply -f /home/ec2-user/deployment.yaml
